### ISSUE TITLE
Decompression rate up to 2x times failes

### ISSUE THREAD

**Issue by relonger** [Altai-man/perl6-Compress-Bzip2#2]
Look at this sub:

```perl6
our sub internalBlobToBlob(buf8 $data, $compressing) {
    my buf8 $temp .= new;
    my uint32 $len;
    given $data.elems {
	when 0..50 {
	    $len = 1024; # Numbers need check.
	}
	default {
	    $len = $data.elems*2;
	}
    }
```

You create temp buffer for decompressed data only up to 2x bigger then the source one. Why do you think compression more then 2x times impossible??? E.g. I compressing html files which compressed up to 5-7x times.

Now I got error:
```Output buffer is definetly smaller than source. Check size of your file or report an error.```

**Comment by Altai-man** [comment]
Hi!

Indeed, such restriction is quite naive. :) This module was written quite a long ago, but I think it is time to fix it. Thanks a lot for your report!

I will see what I can do now.

**Comment by Altai-man** [comment]
Pushed a fix, can you try it out on your side?
